ALPACA_PAPER_KEY: "your-paper-key"
ALPACA_PAPER_SECRET: "your-paper-secret"
ALPACA_PAPER_URL: "https://paper-api.alpaca.markets"
ALPACA_LIVE_KEY: "your-live-key"
ALPACA_LIVE_SECRET: "your-live-secret"
ALPACA_LIVE_URL: "https://api.alpaca.markets"
ALLOW_LIVE: false
PG_URI: "mysql+pymysql://maria:maria@192.168.0.59:3306/quant_fund"
FRED_API_KEY: "your-fred-key"
API_TOKEN: "changeme"
AUTO_START_SCHED: true
API_HOST: "192.168.0.59"
API_PORT: 8001
REDIS_URL: "redis://:changeme@192.168.0.59:6379/0"
CACHE_TTL: 900
CACHE_BACKEND: "memory"
LEDGER_STREAM_MAXLEN: 1000
ALLOC_METHOD: "max_sharpe"
