ALPACA_API_KEY: "your-alpaca-key"
ALPACA_API_SECRET: "your-secret"
ALPACA_BASE_URL: "https://paper-api.alpaca.markets"
PG_URI: "postgresql://postgres:postgres@localhost:5432/quant_fund"
FRED_API_KEY: "your-fred-key"
API_TOKEN: "changeme"
AUTO_START_SCHED: true
