ALPACA_PAPER_KEY: "your-paper-key"
ALPACA_PAPER_SECRET: "your-paper-secret"
ALPACA_PAPER_URL: "https://paper-api.alpaca.markets"
ALPACA_LIVE_KEY: "your-live-key"
ALPACA_LIVE_SECRET: "your-live-secret"
ALPACA_LIVE_URL: "https://api.alpaca.markets"
ALLOW_LIVE: false
PG_URI: "mysql+pymysql://maria:maria@192.168.0.59:3306/quant_fund"
FRED_API_KEY: "your-fred-key"
API_TOKEN: "changeme"
AUTO_START_SCHED: true
API_HOST: "192.168.0.59"
API_PORT: 8001
REDIS_URL: "redis://:changeme@192.168.0.59:6379/0"
# Cron-style schedules for periodic jobs
SCHED_METRICS: "5 0 * * *"
SCHED_TICKER_SCORES: "0 3 1 * *"
SCHED_WSB_MENTIONS: "0 3 1 * *"
SCHED_ACCOUNT: "0 0 * * *"
SCHED_RISK_STATS: "30 0 * * *"
SCHED_RISK_RULES: "*/5 * * * *"
SCHED_POLITICIAN_TRADES: "0 2 * * *"
SCHED_LOBBYING: "30 2 * * 1"
SCHED_WIKI_TRENDING: "0 3 * * *"
SCHED_WIKI_VIEWS: "30 3 * * *"
SCHED_DC_INSIDER: "0 4 * * 1"
SCHED_GOV_CONTRACTS: "0 5 * * *"
SCHED_APP_REVIEWS: "0 6 * * *"
SCHED_GOOGLE_TRENDS: "0 7 * * *"
SCHED_INSIDER_BUYING: "0 8 * * *"
SCHED_VOL_MOM: "0 9 * * *"
SCHED_LEV_SECTOR: "30 9 * * *"
SCHED_SECTOR_MOM: "0 10 * * *"
SCHED_SMALLCAP_MOM: "30 10 * * *"
SCHED_UPGRADE_MOM: "0 11 * * *"
