apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: portfolio-system
  template:
    metadata:
      labels:
        app: portfolio-system
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
