name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Mypy
        run: mypy -p scrapers -p api -p execution -p scheduler
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Pytest
        run: pytest -q
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo integration
  canary:
    runs-on: ubuntu-latest
    steps:
      - run: echo canary
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, unit, integration, canary]
    steps:
      - run: echo deploy
